import * as vscode from 'vscode';
import { detectStack, writeVibeFile, getWorkspacePath } from '../utils/fileReader';
import { findVibeCli, runVibe } from '../utils/cliRunner';
import { t } from '../i18n';
import * as fs from 'fs';
import * as path from 'path';

export async function initCommand(): Promise<void> {
  const wsPath = getWorkspacePath();
  if (!wsPath) {
    vscode.window.showErrorMessage(t('errNoWorkspace'));
    return;
  }

  const projectName = await vscode.window.showInputBox({
    prompt: t('msgProjectName'),
    value: path.basename(wsPath) || 'my-project',
  });
  if (!projectName) return;

  const projectTypeLabel = await vscode.window.showQuickPick(
    [t('typeSaaS'), t('typeEcommerce'), t('typeContent'), t('typeAPI'), t('typeDashboard'), t('typeOther')],
    { placeHolder: t('msgSelectType') }
  );
  if (!projectTypeLabel) return;

  const typeMap: Record<string, string> = {
    [t('typeSaaS')]: 'saas',
    [t('typeEcommerce')]: 'ecommerce',
    [t('typeContent')]: 'content',
    [t('typeAPI')]: 'api',
    [t('typeDashboard')]: 'dashboard',
    [t('typeOther')]: 'other',
  };
  const projectType = typeMap[projectTypeLabel] || 'saas';

  const agentsPath = path.join(wsPath, 'AGENTS.md');
  const agentsExists = fs.existsSync(agentsPath);
  let mergeStrategy: 'merge' | 'overwrite' | 'abort' = 'merge';

  if (agentsExists) {
    const choice = await vscode.window.showWarningMessage(
      t('msgAgentsExists'),
      { modal: false },
      t('cmdMerge'),
      t('cmdOverwrite'),
      t('cmdAbort')
    );
    if (choice === t('cmdAbort') || !choice) return;
    mergeStrategy = choice === t('cmdMerge') ? 'merge' : 'overwrite';
  }

  const config = vscode.workspace.getConfiguration('the-vibecoding-handbook');
  const useLLM = config.get('useLLM', true);
  const cliPath = findVibeCli(wsPath);

  if (cliPath) {
    const args = ['init', '-y', '-t', projectType, '--name', projectName];
    if (mergeStrategy === 'overwrite') args.push('--overwrite');
    if (!useLLM) args.push('--no-llm');

    await vscode.window.withProgress(
      {
        location: vscode.ProgressLocation.Notification,
        title: t('msgInitializing'),
        cancellable: false,
      },
      async () => {
        const result = await runVibe(cliPath, args, wsPath);
        if (result.exitCode !== 0) {
          const detail = result.stderr || result.stdout;
          vscode.window.showErrorMessage(`${t('errCommandFailed')}${detail ? ': ' + detail : ''}`);
        }
      }
    );
  } else {
    // CLI not found: use local heuristic fallback
    vscode.window.showWarningMessage(t('msgCliNotFound'));
    const stack = detectStack();

    await vscode.window.withProgress(
      {
        location: vscode.ProgressLocation.Notification,
        title: t('msgInitializing'),
        cancellable: false,
      },
      async (progress) => {
        progress.report({ increment: 0, message: t('msgCreatingAgents') });
        const agentsContent = generateAgentsMd(projectName, stack);
        if (mergeStrategy === 'merge' && agentsExists) {
          const existing = fs.readFileSync(agentsPath, 'utf-8');
          writeVibeFile('AGENTS.md', mergeIntoExisting(existing, agentsContent));
        } else {
          writeVibeFile('AGENTS.md', agentsContent);
        }

        progress.report({ increment: 25, message: t('msgCreatingIdeRules') });
        writeVibeFile('.iderules', generateIdeRules(stack));

        progress.report({ increment: 50, message: t('msgCreatingPolicies') });
        writeVibeFile('.vibecoding/policies/git-policy.md', generateGitPolicy());
        writeVibeFile('.vibecoding/policies/security-policy.md', generateSecurityPolicy());
        writeVibeFile('.vibecoding/policies/testing-policy.md', generateTestingPolicy());

        progress.report({ increment: 75, message: t('msgCreatingAdr') });
        writeVibeFile(
          '.vibecoding/decisions/ADR-001-architecture.md',
          generateAdr(projectName, projectTypeLabel, stack)
        );

        progress.report({ increment: 100, message: t('msgDone') });
        await new Promise((r) => setTimeout(r, 500));
      }
    );
  }

  const showNotifications = config.get('showNotifications', true);
  if (showNotifications) {
    vscode.window.showInformationMessage(
      t('msgInitSuccess'),
      t('cmdOpenAgents')
    ).then((selection) => {
      if (selection === t('cmdOpenAgents')) {
        vscode.commands.executeCommand('the-vibecoding-handbook.openAgents');
      }
    });
  }
}

function wrapInMarkers(content: string): string {
  return `<!-- vibe:begin — auto-generated by @vibecoding/cli; edit outside these markers -->\n${content.trimEnd()}\n<!-- vibe:end -->\n`;
}

function mergeIntoExisting(existing: string, generated: string): string {
  const BEGIN_PREFIX = '<!-- vibe:begin';
  const END_PREFIX = '<!-- vibe:end';
  const wrapped = wrapInMarkers(generated);
  if (existing.trim() === '') return wrapped;

  const lines = existing.split('\n');
  const beginLine = lines.findIndex((line) => line.includes(BEGIN_PREFIX));
  let endLine = -1;
  if (beginLine !== -1) {
    for (let i = beginLine + 1; i < lines.length; i++) {
      if (lines[i].includes(END_PREFIX)) {
        endLine = i;
        break;
      }
    }
  }

  if (beginLine !== -1 && endLine !== -1) {
    return [
      ...lines.slice(0, beginLine),
      ...wrapped.trimEnd().split('\n'),
      ...lines.slice(endLine + 1),
    ].join('\n');
  }

  return existing.trimEnd() + '\n\n---\n\n' + wrapped;
}

function generateAgentsMd(projectName: string, stack: { framework: string; language: string }): string {
  return `# ${projectName} — Agent Context

> Auto-generated by Vibe Coding VS Code Extension
> Last updated: ${new Date().toISOString().split('T')[0]}

## Overview
A ${stack.framework} project using ${stack.language}.

## Tech Stack

| Layer | Technology |
|-------|-----------|
| Framework | ${stack.framework} |
| Language | ${stack.language} |

## Coding Standards

- ${stack.language === 'TypeScript' ? 'Strict mode enabled — no \`any\` types' : 'Use modern ES2022+ features'}
- Named exports preferred over default exports
- async/await (no .then() chains)
- Max function length: 50 lines

## Security
- Input validation on ALL user inputs
- No hardcoded secrets or API keys
- No console.log in production code

## Git Workflow

| Branch | Purpose |
|--------|---------|
| \`main\` | Production — no direct commits |
| \`dev\` | Integration branch |
| \`feature/*\` | New features |

## Deployment Checklist

- [ ] All tests pass
- [ ] TypeScript compiles without errors
- [ ] No console.log statements
- [ ] Environment variables configured
`;
}

function generateIdeRules(stack: { framework: string; language: string }): string {
  return `# Global Rules

# Framework
- This is a ${stack.framework} project using ${stack.language}
${stack.language === 'TypeScript' ? '- Strict mode — no \`any\` types' : ''}

# Code Style
- Named exports preferred
- async/await (no .then())
- Max function length: 50 lines

# Security
- Input validation on ALL inputs
- No hardcoded secrets
- No console.log in production

# Forbidden
- No eval() or Function()
- No inline styles
`;
}

function generateGitPolicy(): string {
  return `# Git Policy

## Branching Strategy

| Branch | Purpose | Rules |
|--------|---------|-------|
| \`main\` | Production | NO direct commits. PRs only |
| \`develop\` | Integration | Merge feature branches here |
| \`feature/*\` | New features | Branch from develop |

## Commit Convention

\`\`\`
type(scope): description
\`\`\`

Types: feat, fix, docs, test, refactor, security, deps
`;
}

function generateSecurityPolicy(): string {
  return `# Security Policy

## Authentication
- All API routes require valid JWT
- Session timeout: 24 hours

## Data Protection
- Input validation on ALL user inputs
- Output encoding to prevent XSS
- Parameterized queries only

## Environment Variables
- .env files NEVER committed
`;
}

function generateTestingPolicy(): string {
  return `# Testing Policy

## Requirements

| Test Type | Coverage |
|-----------|----------|
| Unit | 60% |
| Integration | Critical paths |
| E2E | User journeys |

## Rules
- One concept per test
- Descriptive names
`;
}

function generateAdr(projectName: string, projectType: string, stack: { framework: string; language: string }): string {
  return `# ADR-001: Architecture Overview

## Status
Accepted

## Context
Building ${projectName} — a ${projectType} project.

## Decision

| Layer | Technology |
|-------|-----------|
| Framework | ${stack.framework} |
| Language | ${stack.language} |

## Date
${new Date().toISOString().split('T')[0]}
`;
}
