import * as vscode from 'vscode';
import { detectStack, writeVibeFile, getWorkspacePath } from '../utils/fileReader';

export async function initCommand(): Promise<void> {
  const wsPath = getWorkspacePath();
  if (!wsPath) {
    vscode.window.showErrorMessage('No workspace folder open.');
    return;
  }

  // Quick picks for project configuration
  const projectName = await vscode.window.showInputBox({
    prompt: 'Project name',
    value: wsPath.split('/').pop() || 'my-project',
  });
  if (!projectName) return;

  const projectType = await vscode.window.showQuickPick(
    ['SaaS / Web App', 'E-commerce', 'Content Platform', 'API / Backend', 'Dashboard', 'Other'],
    { placeHolder: 'Select project type' }
  );
  if (!projectType) return;

  const stack = detectStack();

  // Generate files
  const progress = await vscode.window.withProgress(
    {
      location: vscode.ProgressLocation.Notification,
      title: 'Initializing Vibe Coding governance',
      cancellable: false,
    },
    async (progress) => {
      progress.report({ increment: 0, message: 'Creating AGENTS.md...' });
      writeVibeFile('AGENTS.md', generateAgentsMd(projectName, stack));

      progress.report({ increment: 25, message: 'Creating .cursorrules...' });
      writeVibeFile('.cursorrules', generateCursorRules(stack));

      progress.report({ increment: 50, message: 'Creating policies...' });
      writeVibeFile('.vibecoding/policies/git-policy.md', generateGitPolicy());
      writeVibeFile('.vibecoding/policies/security-policy.md', generateSecurityPolicy());
      writeVibeFile('.vibecoding/policies/testing-policy.md', generateTestingPolicy());

      progress.report({ increment: 75, message: 'Creating ADR...' });
      writeVibeFile(
        '.vibecoding/decisions/ADR-001-architecture.md',
        generateAdr(projectName, projectType, stack)
      );

      progress.report({ increment: 100, message: 'Done!' });
      await new Promise((r) => setTimeout(r, 500));
    }
  );

  vscode.window.showInformationMessage(
    `Vibe Coding governance initialized for ${projectName}!`,
    'Open AGENTS.md'
  ).then((selection) => {
    if (selection === 'Open AGENTS.md') {
      vscode.commands.executeCommand('vibecoding.openAgents');
    }
  });
}

function generateAgentsMd(projectName: string, stack: { framework: string; language: string }): string {
  return `# ${projectName} — Agent Context

> Auto-generated by Vibe Coding VS Code Extension
> Last updated: ${new Date().toISOString().split('T')[0]}

## Overview
A ${stack.framework} project using ${stack.language}.

## Tech Stack

| Layer | Technology |
|-------|-----------|
| Framework | ${stack.framework} |
| Language | ${stack.language} |

## Coding Standards

- ${stack.language === 'TypeScript' ? 'Strict mode enabled — no \`any\` types' : 'Use modern ES2022+ features'}
- Named exports preferred over default exports
- async/await (no .then() chains)
- Max function length: 50 lines

## Security
- Input validation on ALL user inputs
- No hardcoded secrets or API keys
- No console.log in production code

## Git Workflow

| Branch | Purpose |
|--------|---------|
| \`main\` | Production — no direct commits |
| \`develop\` | Integration branch |
| \`feature/*\` | New features |

## Deployment Checklist

- [ ] All tests pass
- [ ] TypeScript compiles without errors
- [ ] No console.log statements
- [ ] Environment variables configured
`;
}

function generateCursorRules(stack: { framework: string; language: string }): string {
  return `# Global Rules

# Framework
- This is a ${stack.framework} project using ${stack.language}
${stack.language === 'TypeScript' ? '- Strict mode — no \`any\` types' : ''}

# Code Style
- Named exports preferred
- async/await (no .then())
- Max function length: 50 lines

# Security
- Input validation on ALL inputs
- No hardcoded secrets
- No console.log in production

# Forbidden
- No eval() or Function()
- No inline styles
`;
}

function generateGitPolicy(): string {
  return `# Git Policy

## Branching Strategy

| Branch | Purpose | Rules |
|--------|---------|-------|
| \`main\` | Production | NO direct commits. PRs only |
| \`develop\` | Integration | Merge feature branches here |
| \`feature/*\` | New features | Branch from develop |

## Commit Convention

\`\`\`
type(scope): description
\`\`\`

Types: feat, fix, docs, test, refactor, security, deps
`;
}

function generateSecurityPolicy(): string {
  return `# Security Policy

## Authentication
- All API routes require valid JWT
- Session timeout: 24 hours

## Data Protection
- Input validation on ALL user inputs
- Output encoding to prevent XSS
- Parameterized queries only

## Environment Variables
- .env files NEVER committed
`;
}

function generateTestingPolicy(): string {
  return `# Testing Policy

## Requirements

| Test Type | Coverage |
|-----------|----------|
| Unit | 60% |
| Integration | Critical paths |
| E2E | User journeys |

## Rules
- One concept per test
- Descriptive names
`;
}

function generateAdr(projectName: string, projectType: string, stack: { framework: string; language: string }): string {
  return `# ADR-001: Architecture Overview

## Status
Accepted

## Context
Building ${projectName} — a ${projectType} project.

## Decision

| Layer | Technology |
|-------|-----------|
| Framework | ${stack.framework} |
| Language | ${stack.language} |

## Date
${new Date().toISOString().split('T')[0]}
`;
}
