export interface DocChapter {
  slug: string;
  title: string;
  description: string;
  sections: DocSection[];
}

export interface DocSection {
  id: string;
  title: string;
  content: string;
}

export const chapters: DocChapter[] = [
  {
    slug: 'fundamentals',
    title: '1. 基础',
    description: '什么是 vibe coding、它的起源以及何时使用它。',
    sections: [
      {
        id: 'what-is-vibe-coding',
        title: '什么是 Vibe Coding？',
        content: `Vibe coding 是一种 AI-first 的开发方法：你用自然语言描述需求，由 AI 智能体生成代码。该术语由 Andrej Karpathy 于 2025 年初提出，此后已发展为一门结构化的学科。

**核心思想**
不必手动编写每一行代码，你要做的是：
1. 描述你需要的功能或修复
2. 提供上下文（你的代码库、模式、约束）
3. 审查 AI 生成的结果
4. 通过精确的后续提示词迭代

**演进：2025 → 2026**
- **2025（狂野西部）**：早期采用者试验 ChatGPT 和 Copilot。大量“vibe”，缺少结构。
- **2026（纪律化）**：专业化工具（Cursor、Claude Code）、上下文工程模式、生产检查清单和安全关卡。Vibe coding 演变为有意识的 vibe coding。

**Vibe Coding vs 无代码 vs 传统开发**

| 方面 | Vibe Coding | 无代码 | 传统开发 |
|------|-------------|--------|----------|
| 代码所有权 | 完全 | 有限 | 完全 |
| 灵活性 | 高 | 低 | 高 |
| 速度 | 非常高 | 高 | 低 |
| 学习曲线 | 中 | 低 | 高 |
| 可投入生产 | 是（需关卡） | 是 | 是 |

**光谱：随性 → 有意识 → 生产就绪**
- **随性**："帮我做个待办应用" —— 快速原型、实验
- **有意识**：结构化提示词、上下文文件、审查清单
- **生产就绪**：安全关卡、测试、CI/CD 集成`,
      },
      {
        id: 'when-to-use',
        title: '何时使用 Vibe Coding',
        content: `**适合使用的情况：**
- 原型设计与 MVP
- 样板代码与脚手架
- 重构重复代码
- 编写测试（尤其是边界情况）
- 文档与注释
- 学习新模式或 API

**不适合使用的情况：**
- 关键安全代码（认证、加密）
- 金融交易与支付处理
- 处理 PII（个人可识别信息）的代码
- 需要深厚领域知识的复杂算法逻辑
- 当你不理解 AI 生成了什么时

**黄金法则**
> 如果你解释不清代码在做什么，就不应该将其上线。Vibe coding 放大你的能力，而不是取代你的理解。`,
      },
    ],
  },
  {
    slug: 'workflow',
    title: '2. 四阶段工作流',
    description: '提示词 → 生成 → 审查 → 优化。获得一致结果的系统化工作流。',
    sections: [
      {
        id: 'phase-1-prompt',
        title: '阶段 1：提示词',
        content: `提示词就是你的需求规格。优秀的提示词包括：

**1. 角色定义**
\`\`\`
You are an expert senior TypeScript developer specializing in 
Next.js applications with 10+ years of experience.
\`\`\`

**2. 上下文**
\`\`\`
We are working on a SaaS dashboard application. The tech stack is:
- Next.js 15 (App Router)
- TypeScript with strict mode
- Tailwind CSS
- Prisma ORM with PostgreSQL
- tRPC for API routes
\`\`\`

**3. 任务描述**
\`\`\`
Implement a user settings page that allows users to:
- Update their profile (name, avatar, bio)
- Change notification preferences
- Manage connected accounts (GitHub, Google)
- Delete their account with confirmation
\`\`\`

**4. 约束与模式**
\`\`\`
- Follow the existing component structure in /src/components
- Use React Server Components where possible
- All forms must use react-hook-form with zod validation
- API routes must be protected with our auth middleware
\`\`\`

**5. 示例（可选但强大）**
\`\`\`
Here's how we handle similar forms: [link to existing code]
The UI should match this design system: [link to Storybook]
\`\`\`

**应避免的反模式：**
- "帮我做个网站"（过于模糊）
- "修复这个"却不指明哪里坏了
- "让它更好"（主观）`,
      },
      {
        id: 'phase-2-generate',
        title: '阶段 2：生成',
        content: `**选择合适的模型**

| 模型 | 最适用于 | 成本 | 速度 |
|------|---------|------|------|
| Claude 4 Sonnet | 大多数编码任务 | $$ | 快 |
| Claude 4 Opus | 复杂架构 | $$$ | 中等 |
| GPT-4o | 快速任务、解释 | $$ | 快 |
| o3-mini | 深度推理 | $$ | 中等 |

**设置上下文**
在生成之前，确保上下文文件已就位：
1. 项目根目录的 **AGENTS.md**
2. IDE 中的 **.iderules**
3. 已配置的 **Skills/Memories**（如果你的工具支持）

**范围控制**
准确告诉智能体要修改什么：
\`\`\`
Only modify files in /src/app/settings/. 
Do not change the auth system or database schema.
Use the existing UI components from /src/components/ui.
\`\`\``,
      },
      {
        id: 'phase-3-review',
        title: '阶段 3：审查',
        content: `**审查清单**

每个生成的改动都必须通过以下关卡：

□ **能否编译？** 首先运行类型检查。
\`\`\`
npm run typecheck
\`\`\`

□ **测试是否通过？**
\`\`\`
npm test
\`\`\`

□ **安全扫描**：检查：
- 硬编码的密钥或 API key
- SQL 注入漏洞
- 用户可见输出中的 XSS 风险
- 不安全的 eval() 或 Function() 使用

□ **架构一致性**：是否遵循现有模式？

□ **无多余依赖**：是否安装了你不需要的包？

□ **边界情况处理**：空状态、错误、加载状态？

□ **可访问性**：合适的 ARIA 标签、键盘导航？

**危险信号 —— 立即拒绝：**
- 类似 "// Generated by AI" 的注释
- 生产代码中遗留的 console.log
- 对 .env 文件或配置的任何改动
- 依赖未知的 npm 包`,
      },
      {
        id: 'phase-4-refine',
        title: '阶段 4：优化',
        content: `**如何高效迭代**

糟糕的优化：
\`\`\`
"This doesn't work. Fix it."
\`\`\`

优秀的优化：
\`\`\`
"The form submission is failing with a 422 error. 
The issue is in the zod schema— the 'bio' field has a max length 
of 100 but the database column allows 500. Update the schema 
to match the database constraint and add proper error messaging 
that shows remaining characters as the user types."
\`\`\`

**STAR 优化法：**
- **S**ituation：当前状态是什么？
- **T**arget：目标状态是什么？
- **A**ction：具体需要改变什么？
- **R**estrictions：什么不应改变？

**何时重新开始**
有时迭代会让情况更糟。在以下情况下重新开始：
- 你已经优化超过 3 次
- 代码越来越复杂
- 智能体似乎陷入循环
- 你有一半生成的内容都看不懂`,
      },
    ],
  },
  {
    slug: 'context-engineering',
    title: '3. 上下文工程',
    description: '差异化所在。如何构建上下文以实现跨文件的精确性。',
    sections: [
      {
        id: 'agents-md',
        title: 'AGENTS.md 模板',
        content: `AGENTS.md 文件位于项目根目录，是处理你代码库的 AI 智能体的“唯一事实来源”。

**模板：**
\`\`\`markdown
# Project Context

## Overview
[Brief description of what this project does]

## Tech Stack
- Framework: [e.g., Next.js 15]
- Language: [e.g., TypeScript 5.7]
- Styling: [e.g., Tailwind CSS v4]
- Database: [e.g., PostgreSQL via Prisma]
- Auth: [e.g., NextAuth.js v5]

## Architecture
- App Router structure in /src/app
- Shared components in /src/components
- Database schema in /prisma/schema.prisma
- API routes via tRPC in /src/server

## Coding Standards
- Use React Server Components by default
- Client components only when needed ("use client")
- All forms use react-hook-form + zod
- API responses follow { success: boolean, data?: T, error?: string }

## Patterns
[Link to or describe key patterns the agent should follow]

## Constraints
- Never expose database connection strings
- Always validate user input server-side
- Use our logger utility, not console.log
\`\`\``,
      },
      {
        id: 'ide-rules',
        title: '.iderules',
        content: `.iderules 文件为任何读取它的 IDE（Cursor、Windsurf、Claude Code 等）中的 AI 智能体提供实时指导。

**示例 .iderules：**
\`\`\`
# Global rules
- Always use TypeScript strict mode
- Prefer Server Components unless interactivity is needed
- Use the existing UI component library
- Follow the established file naming conventions

# Code style
- Use named exports, not default exports
- Props interfaces should be named {ComponentName}Props
- Use async/await, not .then()
- Error handling: always use try/catch with our error utilities

# Forbidden
- No any types
- No console.log in production code
- No inline styles (use Tailwind)
- No direct database queries from components
\`\`\``,
      },
      {
        id: 'anti-patterns',
        title: '上下文反模式',
        content: `**1. 上下文膨胀**
把整个代码库倾倒进上下文窗口。这会混淆智能体并浪费 token。

*修复*：有选择地包含。只包含相关文件和模式。

**2. 相互矛盾的规则**
AGENTS.md 和 .iderules 中的指令相互冲突。

*修复*：保持唯一事实来源。AGENTS.md 用于项目级，.iderules 用于 IDE 特定样式。

**3. 过度规范**
写下 500 行没人会读或维护的规则。

*修复*：控制在 100 行以内。聚焦那 20% 能预防 80% 问题的规则。

**4. 上下文过时**
数月未更新的上下文文件。

*修复*：当你改变技术栈或模式时更新上下文文件。将其加入 PR 检查清单。`,
      },
    ],
  },
  {
    slug: 'tools',
    title: '4. 2026 年工具',
    description: '2026 年主流 AI 编程工具对比指南。',
    sections: [
      {
        id: 'cursor',
        title: 'Cursor',
        content: `**Cursor** —— 为 AI 编程而生的 IDE。

**优点：**
- 原生 AI 集成（无需插件）
- 出色的上下文感知（读取整个代码库）
- Composer 模式支持多文件编辑
- 快速响应

**缺点：**
- VS Code 分支（更新略滞后）
- 自动建议可能过于激进
- 重度使用需付费计划

**最适合：** 全栈开发者、生产代码库
**定价：** 免费版、Pro $20/月、Business $40/用户/月`,
      },
      {
        id: 'claude-code',
        title: 'Claude Code',
        content: `**Claude Code** —— Anthropic 推出的终端型 AI 智能体。

**优点：**
- 擅长复杂架构任务
- 推理与规划能力出色
- 兼容任何编辑器
- 可直接运行命令和测试

**缺点：**
- 仅终端（无 GUI）
- 比 IDE 集成工具慢
- 长时间会话成本更高

**最适合：** 架构决策、复杂重构、CLI 工作流
**定价：** 包含在 Claude Pro（$20/月）中`,
      },
      {
        id: 'windsurf',
        title: 'Windsurf',
        content: `**Windsurf**（前身为 Codeium）—— 具备级联工作流的智能体 IDE。

**优点：**
- Cascade 智能体可规划并执行多步骤任务
- 免费版慷慨
- 上下文理解良好

**缺点：**
- 社区规模小于 Cursor
- 存在一定稳定性问题
- 生态不够成熟

**最适合：** 想要免费且强大的 Cursor 替代方案的开发人员
**定价：** 免费版、Pro $12/月`,
      },
      {
        id: 'others',
        title: '其他工具',
        content: `**v0**（Vercel）
- 最适合：从提示词生成 UI
- 类型：应用构建器
- 定价：免费版、Pro $20/月

**Lovable**
- 最适合：最少代码的全栈应用
- 类型：应用构建器
- 定价：免费版、Pro $20/月

**Replit Agent**
- 最适合：教育、快速原型
- 类型：Cloud IDE + 智能体
- 定价：免费版、Core $7/月

**Zed**
- 最适合：追求速度的开发人员
- 类型：原生 IDE（Rust）
- 定价：免费（开源）

**Aider**
- 最适合：终端爱好者、Git 原生工作流
- 类型：CLI 工具
- 定价：免费（开源）`,
      },
    ],
  },
  {
    slug: 'prompting',
    title: '5. 面向开发者的提示词工程',
    description: '专门针对编码任务的提示词工程技术。',
    sections: [
      {
        id: 'prompt-patterns',
        title: '提示词模式',
        content: `**RICE 模式**
- **R**ole：定义 AI 应该扮演谁
- **I**nstruction：要做什么
- **C**ontext：背景信息
- **E**xpectation：期望的输出格式

**Chain-of-Thought 模式**
让 AI 一步步思考：
\`\`\`
"Before writing any code, plan the implementation:
1. What components will you need?
2. What API endpoints?
3. What database changes?
4. Share your plan, then implement."
\`\`\`

**Few-Shot 模式**
提供期望输出的示例：
\`\`\`
"Here are examples of how we write API routes:
[example 1]
[example 2]

Now write a route for user preferences following the same pattern."
\`\`\``,
      },
      {
        id: 'prompt-library',
        title: '提示词库',
        content: `访问我们的交互式 **提示词库**，地址 /prompts，包含 50 多个即拿即用的提示词，按以下维度组织：

- **任务类型**：Feature、bugfix、refactor、test、docs
- **工具**：Cursor、Claude Code、Windsurf
- **技术栈**：Next.js、Python、Rust 等

每个提示词包含：
- 完整提示词文本（一键复制）
- 使用场景
- 预期输出
- 常用后续提示词`,
      },
    ],
  },
  {
    slug: 'stack-patterns',
    title: '6. 技术栈模式',
    description: '经受过实战考验的 AI-first 开发技术栈组合。',
    sections: [
      {
        id: 'nextjs-stack',
        title: 'Next.js + TypeScript + Tailwind',
        content: `**推荐技术栈**

\`\`\`
Next.js 15 (App Router)
├── TypeScript 5.7 (strict)
├── Tailwind CSS v4
├── shadcn/ui components
├── Prisma ORM
├── PostgreSQL
├── tRPC or Server Actions
├── NextAuth.js v5
└── Vercel (deploy)
\`\`\`

**为什么这个技术栈适合 vibe coding？**
- TypeScript 能捕获 AI 生成的类型错误
- Tailwind 易于被 AI 正确生成
- shadcn/ui 提供一致的组件模式
- Prisma 模式是自描述的
- App Router 为 AI 智能体提供清晰的边界`,
      },
      {
        id: 'project-structure',
        title: '项目结构',
        content: `**对 AI 友好的文件夹结构：**

\`\`\`
my-app/
├── AGENTS.md              # Project context
├── .iderules              # IDE rules
├── src/
│   ├── app/               # Next.js App Router
│   │   ├── (auth)/        # Route groups
│   │   ├── api/           # API routes
│   │   └── layout.tsx
│   ├── components/        # React components
│   │   ├── ui/            # shadcn/ui components
│   │   └── [features]/    # Feature components
│   ├── lib/               # Utilities
│   ├── hooks/             # Custom hooks
│   ├── types/             # Shared types
│   └── server/            # Server-only code
├── prisma/
│   └── schema.prisma
└── tests/
\`\`\``,
      },
    ],
  },
  {
    slug: 'security',
    title: '7. 安全与生产',
    description: 'AI 生成代码的安全关卡与最佳实践。',
    sections: [
      {
        id: 'security-mindset',
        title: '安全心态',
        content: `**将 AI 输出视为不可信代码**

AI 生成的每一行代码都应像一位你从未谋面的初级开发者提交的 PR 一样接受审查。

**三层防御：**
1. **生成前**：上下文文件中的明确约束
2. **生成后**：自动化安全扫描
3. **部署前**：关键路径的人工审查

**关键路径（必须人工审查）：**
- 认证与授权
- 支付处理
- 数据加密
- PII 处理
- API 速率限制`,
      },
      {
        id: 'security-tools',
        title: '安全工具',
        content: `**必备安全栈：**

| 工具 | 用途 |
|------|------|
| GitLeaks | 提交中的密钥检测 |
| npm audit | 依赖漏洞扫描 |
| Snyk | 持续依赖监控 |
| ESLint security plugin | 安全静态分析 |
| OWASP ZAP | 动态应用安全测试 |

**预提交钩子：**
\`\`\`json
{
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged && npm run security:check"
    }
  }
}
\`\`\``,
      },
    ],
  },
  {
    slug: 'multi-agent',
    title: '8. 多智能体工作流',
    description: '多个 AI 智能体协同工作的高级模式。',
    sections: [
      {
        id: 'agent-roles',
        title: '智能体角色',
        content: `**智能体管弦乐队**

现代 vibe coding 使用专业化智能体：

1. **规划者**：分析需求并制定实现计划
2. **实现者**：编写实际代码
3. **审查者**：检查代码质量、安全性和一致性
4. **测试者**：生成并运行测试

**示例工作流：**
\`\`\`
[Planner] "Break down this feature into tasks"
    ↓
[Implementer] "Write the code for task 1"
    ↓
[Reviewer] "Review this code against our standards"
    ↓
[Tester] "Write tests for this implementation"
    ↓
[Human] Final review and merge
\`\`\``,
      },
      {
        id: 'subagents',
        title: '何时使用子智能体',
        content: `**何时使用子智能体：**
- 任务跨越多个领域（前端 + 后端 + 数据库）
- 需要并行探索不同方案
- 代码库很大，需要专业知识

**何时不使用子智能体：**
- 任务简单且定义明确
- 智能体之间共享上下文困难
- 你仍在学习 vibe coding 的基础`,
      },
    ],
  },
  {
    slug: 'anti-patterns',
    title: '9. 反模式与调试',
    description: '常见错误及如何恢复。',
    sections: [
      {
        id: 'common-mistakes',
        title: '常见错误',
        content: `**“全部接受”而不审查**
第一大错误。AI 生成的代码看起来合理且能编译，但暗藏 subtle bug。

*修复*：始终审查。使用第 2 章的审查清单。

**隐形技术债务**
AI 倾向于：
- 复制代码而不是抽象
- 添加不必要的依赖
- 跳过错误处理
- 写出过度复杂的解决方案

*修复*：定期进行重构。定期让 AI “简化这段代码”。

**上下文丢失**
长时间对话中 AI 忘记之前的决策。

*修复*：为新功能开启新会话。经常引用你的 AGENTS.md。`,
      },
      {
        id: 'recovery',
        title: '挽救混乱的项目',
        content: `**混乱 Vibe Coded 项目恢复计划：**

1. **停止生成** —— 深呼吸并评估
2. **记录目标架构** —— 写下系统应该是什么样子
3. **创建一个干净分支** —— 不要丢失进度
4. **从测试开始** —— 为想要的行为编写测试
5. **针对测试生成** —— 用 AI 让测试通过
6. **无情重构** —— 删除死代码、合并重复
7. **更新上下文文件** —— 防止未来混乱

**预防胜于治疗：**
- 尽早设置 CI/CD
- 从第一天开始写测试
- 审查每个 PR（即使是 AI 的）
- 保持上下文文件最新`,
      },
    ],
  },
  {
    slug: 'resources',
    title: '10. 资源',
    description: 'Awesome 列表、社区和值得关注的账号。',
    sections: [
      {
        id: 'awesome-list',
        title: 'Awesome Vibe Coding',
        content: `**精选资源：**

**社区：**
- r/cursor —— Cursor 专属讨论
- r/vibecoding —— 综合 vibe coding 社区
- Discord：Vibe Coder Collective

**Newsletters：**
- Vibe Check Weekly
- AI-Assisted Dev Monthly

**值得关注的人：**
- @karpathy —— Andrej Karpathy（提出“vibe coding”）
- @mengto —— 设计 + AI
- @shadcn —— UI 组件大师

**值得关注的工具：**
- 关注我们的 /tools 页面获取最新动态`,
      },
      {
        id: 'changelog',
        title: '更新日志',
        content: `**The Vibe Coding Handbook — 更新日志**

**v1.0（2026-01）**
- 首次发布
- 10 章
- 50+ 提示词
- 工具对比矩阵

**路线图：**
- v1.1：西班牙语翻译、视频指南
- v1.2：高级多智能体模式
- v2.0：社区贡献的案例研究`,
      },
    ],
  },
];

export function getChapterBySlug(slug: string): DocChapter | undefined {
  return chapters.find((c) => c.slug === slug);
}

export function getAllSlugs(): string[] {
  return chapters.map((c) => c.slug);
}
