/**
 * `vibe help` — rich, topic-based help.
 * `vibe help` shows the overview; `vibe help <command>` shows deep detail
 * (options, modes, files, examples). `vibe help modes` shows the
 * interactive / non-interactive matrix for every command.
 */
import { c, header, section, divider } from '../utils/ui.js';
import { renderBanner } from '../utils/banner.js';

interface HelpLine {
  flag: string;
  description: string;
}

interface HelpExample {
  cmd: string;
  note: string;
}

interface CommandHelp {
  summary: string;
  description: string;
  usage: string;
  options?: HelpLine[];
  modes?: HelpLine[];
  files?: HelpLine[];
  examples: HelpExample[];
  tips?: string[];
}

const COMMAND_ORDER = ['init', 'context', 'check', 'review', 'optimize', 'chat', 'sync'];

const COMMAND_SUMMARIES: Record<string, string> = {
  init: 'Initialize project governance (AGENTS.md, .iderules, policies)',
  context: 'Update AGENTS.md from the current codebase',
  check: 'Validate project setup (score + CI-ready exit codes)',
  review: 'Review changed files against project policies',
  optimize: 'Turn a vague prompt into a structured, high-signal prompt',
  chat: 'Interview-style planning: from idea to plan + prompt',
  sync: 'Browse bundled starter templates and the prompt library',
};

const TOPICS: Record<string, CommandHelp> = {
  init: {
    summary: 'Initialize project governance files',
    description:
      'Scans your codebase (framework, language, database, auth, payments, testing, styling, API style — monorepo-aware) and generates a complete governance setup for AI coding agents. When an OpenAI or Anthropic API key is present, AGENTS.md is generated by the LLM from the project scan; otherwise local heuristics are used. Only the stack summary is sent — never source file contents. With --describe, an LLM writes AGENTS.md from your description plus the detected stack. Existing AGENTS.md files are merged by default (preserving your notes outside the markers); use --overwrite to replace them.',
    usage: 'vibe init [options]',
    options: [
      { flag: '-y, --yes', description: 'Skip all prompts and accept detected defaults (CI-friendly)' },
      { flag: '-t, --type <type>', description: 'Project type: saas, ecommerce, api, dashboard, content' },
      { flag: '--name <name>', description: 'Project name (overrides detected folder/package name)' },
      { flag: '--describe <text>', description: 'Generate AGENTS.md from a natural-language description (requires OPENAI_API_KEY or ANTHROPIC_API_KEY)' },
      { flag: '--merge', description: 'Merge into an existing AGENTS.md via managed markers (preserves your edits outside <!-- vibe:begin/end -->)' },
      { flag: '--overwrite', description: 'Replace an existing AGENTS.md completely instead of merging' },
      { flag: '--no-llm', description: 'Skip the LLM and generate AGENTS.md from local heuristics only' },
    ],
    modes: [
      { flag: 'Interactive', description: 'asks project name + type; when AGENTS.md exists, choose merge/overwrite/abort' },
      { flag: 'Non-interactive', description: '-y (or no TTY): runs with detected defaults, merges into existing AGENTS.md — safe for CI' },
      { flag: 'AI mode', description: 'API key detected: LLM writes AGENTS.md from the project scan; --describe uses your description instead' },
    ],
    files: [
      { flag: 'AGENTS.md', description: 'project context for AI agents' },
      { flag: '.iderules', description: 'IDE rules for AI-compatible editors' },
      { flag: '.vibecoding/policies/*.md', description: 'git, security, testing and deployment policies' },
      { flag: '.vibecoding/decisions/ADR-001-architecture.md', description: 'your first architecture decision record' },
    ],
    examples: [
      { cmd: 'vibe init', note: 'interactive setup' },
      { cmd: 'vibe init -y -t saas', note: 'no prompts, SaaS defaults — CI-friendly' },
      { cmd: 'vibe init --describe "booking SaaS with Stripe"', note: 'LLM-generated AGENTS.md from a description' },
      { cmd: 'vibe init --overwrite', note: 'replace an existing AGENTS.md completely' },
      { cmd: 'vibe init --no-llm', note: 'force local heuristic generation' },
    ],
    tips: ['Run `vibe check` afterwards to validate the setup.', 'Use --describe when you have a clear project idea but no code yet.', 'Existing AGENTS.md is merged by default; use --overwrite only when you want a fresh start.'],
  },

  context: {
    summary: 'Regenerate AGENTS.md from the current codebase',
    description:
      'Re-scans the project and rewrites AGENTS.md and .iderules so they never go stale. Detects monorepos — npm/yarn/pnpm/lerna workspaces, or inferred from the directory structure when no tooling is declared. When an API key is present, AGENTS.md is generated by the LLM from the project scan; use --no-llm to force local heuristics. With --describe, an LLM rewrites AGENTS.md from your description plus the scan; only the description and stack summary are sent. Existing AGENTS.md is merged by default (preserving your notes outside the markers); use --overwrite to replace it completely.',
    usage: 'vibe context [options]',
    options: [
      { flag: '-a, --auto', description: 'Auto-detect everything (no prompts)' },
      { flag: '--describe <text>', description: 'Generate AGENTS.md from a natural-language description (requires OPENAI_API_KEY or ANTHROPIC_API_KEY)' },
      { flag: '--dry-run', description: 'Print a preview (first 30 lines) without writing anything' },
      { flag: '--merge', description: 'Merge into the existing AGENTS.md via managed markers (default when AGENTS.md exists)' },
      { flag: '--overwrite', description: 'Replace an existing AGENTS.md completely instead of merging' },
      { flag: '--no-llm', description: 'Skip the LLM and generate AGENTS.md from local heuristics only' },
    ],
    files: [
      { flag: 'AGENTS.md', description: 'rewritten (or merged) with fresh scan results' },
      { flag: '.iderules', description: 'regenerated from the detected stack' },
    ],
    examples: [
      { cmd: 'vibe context --dry-run', note: 'safe preview — writes nothing' },
      { cmd: 'vibe context --merge', note: 'refresh the managed block, keep your notes' },
      { cmd: 'vibe context --overwrite', note: 'replace AGENTS.md completely' },
      { cmd: 'vibe context --describe "booking SaaS with Stripe"', note: 'LLM-generated AGENTS.md from a description' },
      { cmd: 'vibe context --no-llm', note: 'force local heuristic refresh' },
      { cmd: 'vibe context', note: 'run at a monorepo root to see the package table' },
    ],
    tips: ['Use --dry-run liberally; it never touches your files.', 'Use --describe to realign AGENTS.md with a new product direction.', 'Use --no-llm in CI or when you do not want any LLM calls.', 'Existing AGENTS.md is merged by default; use --overwrite only when you want a fresh start.'],
  },

  check: {
    summary: 'Validate project setup against vibe coding policies',
    description:
      'Runs governance checks — AGENTS.md, .iderules, .vibecoding/, git repo, .gitignore covering .env, framework detection, test/lint/typecheck scripts, and obvious exposed secrets — and prints a score.',
    usage: 'vibe check [options]',
    options: [{ flag: '--strict', description: 'Warnings also count as failures' }],
    modes: [
      { flag: 'Exit 0', description: 'all checks passed (or only warnings, non-strict)' },
      { flag: 'Exit 1', description: 'failures found — or warnings with --strict. CI-ready gating' },
    ],
    examples: [
      { cmd: 'vibe check', note: 'local validation with score' },
      { cmd: 'vibe check --strict', note: 'CI mode: warnings fail the build' },
    ],
    tips: ['Adopt --strict in CI once warnings are under control.'],
  },

  review: {
    summary: 'Review changed files against project policies',
    description:
      'Heuristic review of your changes: console.log, explicit any, hardcoded secrets, .then() chains and oversized functions. Adapts to your .iderules / AGENTS.md. Score: 100 − 15 per error − 5 per warning. With --fix it removes standalone console.log statements and suggests how to fix the rest. With --base you can review PR diffs; --strict makes it fail the build on errors or warnings.',
    usage: 'vibe review [options]',
    options: [
      { flag: '-s, --staged', description: 'Review only git staged files' },
      { flag: '-f, --file <file>', description: 'Review a single file' },
      { flag: '--fix', description: 'Auto-fix safe issues (removes console.log), suggests fixes for the rest' },
      { flag: '--base <ref>', description: 'Review files changed since a git ref (e.g. origin/main)' },
      { flag: '--strict', description: 'Exit code 1 when errors or warnings are found (CI mode)' },
    ],
    modes: [
      { flag: 'Default', description: 'reviews modified-but-unstaged files (git diff)' },
      { flag: 'PR mode', description: '--base origin/main reviews the PR diff' },
    ],
    examples: [
      { cmd: 'vibe review -s', note: 'pre-commit: only what is staged' },
      { cmd: 'vibe review -f src/auth.ts', note: 'single file' },
      { cmd: 'vibe review --fix', note: 'strip console.log and get fix suggestions' },
      { cmd: 'vibe review --base origin/main --strict', note: 'CI: fail the PR on review findings' },
    ],
    tips: ['Works great as a pre-commit step before handing code to an AI agent. Run --fix first to clear the trivial noise. Use --base origin/main --strict in PR workflows.'],
  },

  optimize: {
    summary: 'Turn a vague prompt into a structured, high-signal prompt',
    description:
      'Detects intent (feature, bugfix, refactor, test, docs, review — English and Spanish keywords), picks a pattern (RICE, STAR, Chain-of-Thought, Few-Shot, Structured) and enriches the prompt with your AGENTS.md context. With OPENAI_API_KEY or ANTHROPIC_API_KEY in the environment, the final prompt is rewritten by the LLM (VIBE_PROVIDER / VIBE_MODEL to override); without a key, local heuristics.',
    usage: 'vibe optimize [prompt] [options]',
    options: [
      { flag: '-f, --file <file>', description: 'Read the prompt from a file (takes precedence over [prompt])' },
      { flag: '-c, --context <file>', description: 'Read context from this file instead of AGENTS.md' },
      { flag: '-o, --output <file>', description: 'Write the optimized prompt to this file' },
    ],
    modes: [
      { flag: 'Interactive', description: 'asks for the prompt, offers clipboard copy and save' },
      { flag: 'Non-interactive', description: 'auto-saves to optimized-prompt.md (or --output path)' },
      { flag: 'AI mode', description: 'API key detected: LLM rewrites the optimized prompt body' },
    ],
    examples: [
      { cmd: 'vibe optimize "create a login form"', note: 'inline prompt' },
      { cmd: 'vibe optimize -f draft.md -o final.md', note: 'file in, file out' },
      { cmd: 'vibe optimize "fix CORS error" -c CONTEXT.md', note: 'custom context source' },
    ],
    tips: ['Token estimate assumes ~4 characters per token.'],
  },

  chat: {
    summary: 'Interview-style planning: from idea to plan + prompt',
    description:
      'Detects the topic of your task, asks 3 clarifying questions, scans your project, and produces a step-by-step plan plus an optimized prompt ready to paste into your AI agent. With OPENAI_API_KEY or ANTHROPIC_API_KEY in the environment, the plan and prompt are generated by the LLM (VIBE_PROVIDER / VIBE_MODEL to override); without a key, local heuristics. Only your task and stack summary are sent — never file contents.',
    usage: 'vibe chat [task]',
    modes: [
      { flag: 'Interactive', description: '3 follow-up questions about your task' },
      { flag: 'Non-interactive', description: 'auto-generated answers; saves both files' },
    ],
    files: [
      { flag: 'vibe-plan.md', description: 'understanding, steps and checklist' },
      { flag: 'vibe-prompt.md', description: 'the optimized prompt for your agent' },
    ],
    examples: [{ cmd: 'vibe chat "build a sales dashboard"', note: 'plan + prompt in one pass' }],
    tips: ['Set OPENAI_API_KEY or ANTHROPIC_API_KEY for AI-generated plans; without a key it structures your input locally. Paste the result into Cursor or Claude Code.'],
  },

  sync: {
    summary: 'Browse bundled starter templates and the prompt library',
    description:
      'Pick a starter template (next-saas, react-dashboard, api-service) to generate AGENTS.md + .iderules + policies, or browse categorized prompt patterns (components, auth, database, testing) to copy or save.',
    usage: 'vibe sync [options]',
    options: [
      { flag: '--templates', description: 'Only the templates flow' },
      { flag: '--prompts', description: 'Only the prompts flow' },
    ],
    modes: [{ flag: 'Interactive only', description: 'requires a TTY — exits with an error otherwise' }],
    examples: [
      { cmd: 'vibe sync', note: 'templates + prompts' },
      { cmd: 'vibe sync --templates', note: 'starter templates only' },
    ],
    tips: ['Everything is bundled with the CLI — works offline.'],
  },
};

const MODES_MATRIX: HelpLine[] = [
  { flag: 'init', description: 'interactive prompts · -y (or no TTY) = defaults, never blocks' },
  { flag: 'context', description: '--dry-run = read-only preview · otherwise writes AGENTS.md' },
  { flag: 'check', description: 'always read-only · --strict gates CI on warnings' },
  { flag: 'review', description: 'default: unstaged changes · -s staged · -f single file' },
  { flag: 'optimize', description: 'interactive (clipboard + save) · no TTY = auto-save to file' },
  { flag: 'chat', description: 'interactive (3 questions) · no TTY = auto answers · API key = AI mode, else heuristics' },
  { flag: 'sync', description: 'interactive only — requires a TTY' },
];

/** Pads to `width`, guaranteeing at least a 2-space gap for long values. */
function pad(text: string, width: number): string {
  return text.length >= width ? text + '  ' : text.padEnd(width);
}

/** Prints a padded "flag — description" line. */
function line(flag: string, description: string): void {
  console.log('  ' + c.cyan(pad(flag, 34)) + c.dim(description));
}

function renderOverview(): void {
  renderBanner();
  section('Usage');
  console.log('  ' + c.bold('vibe <command> [options]'));

  section('Commands');
  for (const name of COMMAND_ORDER) {
    line(name, COMMAND_SUMMARIES[name]);
  }
  line('help [command]', 'This guide — try `vibe help <command>`');

  section('Modes');
  line('Interactive', 'full prompts, clipboard, choices (requires a TTY)');
  line('Non-interactive', 'piped/CI: sensible defaults, files auto-saved');
  console.log(c.dim('  Details per command: ') + c.cyan('vibe help modes'));

  section('Quick start');
  console.log(c.dim('  cd your-project'));
  console.log('  ' + c.mint('vibe init') + c.dim('          # generate governance files'));
  console.log('  ' + c.mint('vibe check') + c.dim('         # validate the setup'));
  console.log('  ' + c.mint('vibe optimize "..."') + c.dim('  # level up a prompt'));

  section('More');
  line('-v, --version', 'show version number');
  line('-h, --help', 'quick auto-generated reference');
  line('vibe help <command>', 'deep dive: options, modes, files, examples');
  console.log();
  console.log(c.dim('  Docs: https://vibecoding.guide/#/docs'));
  console.log(c.dim('  Repo: https://github.com/dangelBorges/the-vibecoding-handbook'));
  console.log();
}

function renderModes(): void {
  header('VIBE — Interactive vs non-interactive');
  section('Modes per command');
  for (const row of MODES_MATRIX) {
    line(row.flag, row.description);
  }
  console.log();
  console.log(c.dim('  TTY = a real terminal. Piped stdin/stdout (CI, scripts) disables') + '\n' + c.dim('  interactivity; commands fall back to safe non-blocking behavior.'));
  console.log();
}

function renderTopic(name: string, topic: CommandHelp): void {
  header(`VIBE ${name.toUpperCase()} — ${topic.summary}`);
  console.log(c.dim('  ' + topic.description));

  section('Usage');
  console.log('  ' + c.bold(topic.usage));

  if (topic.options?.length) {
    section('Options');
    for (const o of topic.options) line(o.flag, o.description);
  }
  if (topic.modes?.length) {
    section('Modes');
    for (const m of topic.modes) line(m.flag, m.description);
  }
  if (topic.files?.length) {
    section('Files');
    for (const f of topic.files) line(f.flag, f.description);
  }

  section('Examples');
  for (const e of topic.examples) {
    console.log('  ' + c.mint(pad(e.cmd, 44)) + c.dim('# ' + e.note));
  }

  if (topic.tips?.length) {
    section('Tips');
    for (const t of topic.tips) console.log(c.dim('  • ' + t));
  }
  console.log();
}

export function helpCommand(topic?: string): void {
  if (!topic) return renderOverview();
  if (topic === 'modes') return renderModes();

  const found = TOPICS[topic];
  if (!found) {
    console.log(c.error(`  ✖ Unknown topic "${topic}".`));
    console.log(c.dim('  Available: ' + [...COMMAND_ORDER, 'modes'].join(', ')));
    process.exit(1);
  }
  renderTopic(topic, found);
  divider();
  console.log(c.dim('  Back to overview: ') + c.cyan('vibe help'));
  console.log();
}
