import type { DetectedStack } from './fileReader';

export type ChatTopic = 'feature' | 'bugfix' | 'refactor' | 'test' | 'docs' | 'unknown';

export interface ChatMessage {
  role: 'user' | 'assistant';
  content: string;
}

export interface ChatSession {
  topic: ChatTopic;
  messages: ChatMessage[];
  plan?: string;
}

export const clarifyingQuestions: Record<ChatTopic, string[]> = {
  feature: [
    'What is the core user story? (e.g., "As a user, I want to...")',
    'Which existing components or pages will this affect?',
    'Are there any design references or mockups?',
    'What is the expected behavior on mobile?',
  ],
  bugfix: [
    'What is the exact error message or unexpected behavior?',
    'Steps to reproduce? (1. Go to... 2. Click... 3. See...)',
    'Which browser/device does this affect?',
    'When did this last work correctly?',
  ],
  refactor: [
    'What is the current pain point with this code?',
    'What should the improved architecture look like?',
    'Are there tests that must continue passing?',
    'Any dependencies or consumers to consider?',
  ],
  test: [
    'What functionality needs test coverage?',
    'Unit, integration, or E2E tests?',
    'Are there existing tests to use as patterns?',
    'Any external services that need mocking?',
  ],
  docs: [
    'Who is the target audience? (devs, users, API consumers)',
    'What format? (README, inline comments, API docs)',
    'Are there code examples to include?',
  ],
  unknown: [
    'What are you trying to accomplish?',
    'Is this a new feature, bug fix, or improvement?',
    'Any specific files or components involved?',
    'What does "done" look like for this task?',
  ],
};

export function detectTopic(input: string): ChatTopic {
  const lower = input.toLowerCase();
  if (lower.includes('bug') || lower.includes('fix') || lower.includes('error') || lower.includes('broken') || lower.includes('crash')) return 'bugfix';
  if (lower.includes('test') || lower.includes('spec') || lower.includes('coverage')) return 'test';
  if (lower.includes('refactor') || lower.includes('clean') || lower.includes('restructure') || lower.includes('simplify')) return 'refactor';
  if (lower.includes('doc') || lower.includes('readme') || lower.includes('comment') || lower.includes('explain')) return 'docs';
  if (lower.includes('create') || lower.includes('add') || lower.includes('build') || lower.includes('implement') || lower.includes('feature') || lower.includes('page') || lower.includes('component')) return 'feature';
  return 'unknown';
}

export function getAgentsMdContext(agentsContent: string): string {
  const stackMatch = agentsContent.match(/## Tech Stack[\s\S]*?(?=\n## |$)/);
  const standardsMatch = agentsContent.match(/## Coding Standards[\s\S]*?(?=\n## |$)/);
  return [stackMatch?.[0], standardsMatch?.[0]].filter(Boolean).join('\n\n');
}

export function generatePlan(session: ChatSession): string {
  const answers = session.messages
    .filter((m) => m.role === 'user' && m.content.length > 5)
    .map((m) => `- ${m.content}`)
    .join('\n');

  return `# Plan: ${session.topic.charAt(0).toUpperCase() + session.topic.slice(1)}

## Understanding
${answers}

## Steps
1. Review requirements and ask clarifying questions
2. Analyze existing code for patterns and conventions
3. Implement changes incrementally
4. Write/update tests
5. Verify against constraints

## Questions to Consider
- [ ] Does this affect existing data or users?
- [ ] Are there performance implications?
- [ ] Should this be behind a feature flag?
- [ ] What is the rollback plan?

---
Generated by Vibe Coding — vibe chat`;
}

export function generateOptimizedPrompt(session: ChatSession, stack: DetectedStack, agentsContext: string): string {
  const roleMap: Record<ChatTopic, string> = {
    feature: 'Senior Developer',
    bugfix: 'Debug Assistant',
    test: 'Test Engineer',
    refactor: 'Software Architect',
    docs: 'Technical Writer',
    unknown: 'Software Engineer',
  };

  const constraintsMap: Record<ChatTopic, string> = {
    feature: `- TypeScript strict mode — no \`any\` types\n- Follow existing ${stack.framework} patterns\n- Write tests (Arrange-Act-Assert)\n- Handle edge cases and errors\n- Ensure accessibility (ARIA labels)\n- Named exports, async/await, max 50 lines per function`,
    bugfix: `- Minimal changes only\n- Add regression test that fails before fix\n- Explain root cause first\n- Verify no other functionality breaks`,
    test: `- Arrange-Act-Assert pattern\n- Mock ALL external dependencies\n- Test edge cases: null, undefined, empty, errors\n- Descriptive names: "should [expected] when [condition]"`,
    refactor: `- Maintain backward compatibility\n- ALL existing tests must pass\n- Explain reasoning before implementation\n- Incremental changes, verify after each`,
    docs: `- Include practical code examples\n- Document all parameters and return types\n- Note edge cases and limitations\n- Keep it concise but complete`,
    unknown: `- TypeScript strict mode\n- Follow existing patterns\n- Write tests\n- Ask clarifying questions if unclear`,
  };

  const userAnswers = session.messages
    .filter((m) => m.role === 'user')
    .map((m) => m.content)
    .join('\n');

  return `# ${roleMap[session.topic] || 'Software Engineer'}

${agentsContext ? `## Project Context\n${agentsContext}\n` : ''}## Task
${userAnswers}

## Constraints
${constraintsMap[session.topic] || constraintsMap.unknown}

## Before You Start
1. Share your plan before writing any code
2. Break complex tasks into smaller steps
3. Ask clarifying questions if anything is unclear

## Expected Output
Production-ready code with tests, error handling, and TypeScript types.`;
}
