export interface Template {
  name: string;
  description: string;
  files: Record<string, string>;
}

export interface PromptItem {
  name: string;
  description: string;
  prompt: string;
}

export const defaultGitPolicy = `# Git Policy

## Workflow
- main: production only
- develop: integration
- feature/*: new features
- hotfix/*: urgent fixes

## Commits
Format: type(scope): description
Types: feat, fix, docs, test, refactor, security, deps, chore
`;

export const defaultSecurityPolicy = `# Security Policy

## Rules
- NEVER commit .env files
- Input validation on ALL user inputs
- No raw SQL queries
- Rate limiting: 100 req/min IP
- Auth required on all sensitive endpoints
`;

export const TEMPLATES: Record<string, Template> = {
  'next-saas': {
    name: 'Next.js SaaS Starter',
    description: 'Full-stack SaaS with Auth, Stripe, Tailwind, Prisma',
    files: {
      'AGENTS.md': `# Next.js SaaS — Agent Context

> Auto-generated template for SaaS projects

## Overview
A Next.js 14+ SaaS application with authentication, payments, and database.

## Tech Stack

| Layer | Technology |
|-------|-----------|
| Framework | Next.js 14 (App Router) |
| Language | TypeScript (strict) |
| Styling | Tailwind CSS |
| UI | shadcn/ui |
| Auth | NextAuth.js v5 |
| Database | PostgreSQL + Prisma |
| Payments | Stripe |
| Testing | Vitest + React Testing Library |

## Architecture

### Authentication Flow
- OAuth 2.0 + Credentials provider
- JWT sessions with refresh tokens
- Middleware route protection
- Role-based access (user, admin)

### Database Schema (Prisma)
\`\`\`prisma
model User {
  id        String   @id @default(cuid())
  email     String   @unique
  name      String?
  role      Role     @default(USER)
  createdAt DateTime @default(now())
}

enum Role {
  USER
  ADMIN
}
\`\`\`

### Payment Integration (Stripe)
- Checkout sessions for subscriptions
- Webhook handlers for events
- Customer portal for management
- Test mode for development

## Coding Standards

### TypeScript
- Strict mode enabled — no \`any\` types
- All functions must have typed parameters
- Use interfaces for object shapes

### Next.js
- Server Components by default
- Client components with \`"use client"\` directive
- Route handlers for API endpoints
- Server Actions for mutations

### Styling
- Tailwind utility classes
- \`cn()\` helper for conditional classes
- shadcn/ui components as base
- CSS variables for theme tokens

### Testing
- Vitest for unit tests
- React Testing Library for components
- MSW for API mocking
- Coverage target: 80%

## Security Rules

### Authentication
- All API routes require auth (except public)
- Server-side session validation
- CSRF protection on forms
- Rate limiting: 5 login attempts per IP per minute

### Data Protection
- Input validation with Zod schemas
- Output encoding to prevent XSS
- Parameterized Prisma queries
- No raw SQL under any circumstance

### Environment Variables
- NEVER commit .env files
- Use .env.local for secrets
- Validate env vars at startup
- Separate keys for dev/staging/prod

## Git Workflow

| Branch | Purpose |
|--------|---------|
| \`main\` | Production deploys |
| \`develop\` | Integration |
| \`feature/*\` | New features |
| \`hotfix/*\` | Production fixes |

## Scripts

- \`npm run dev\` — Development server
- \`npm run build\` — Production build
- \`npm run test\` — Run tests
- \`npm run db:migrate\` — Database migrations
- \`npm run db:seed\` — Seed data
- \`npm run db:studio\` — Prisma Studio

---
*Generated by Vibe Coding — vibe sync --templates*
`,
      '.iderules': `# Next.js SaaS — IDE Rules

# Framework
- This is a Next.js 14+ project using TypeScript strict mode
- App Router with Server Components by default
- Client components only with \`"use client"\` directive

# Code Style
- Named exports preferred (\`export function\`, not \`export default\`)
- async/await (no .then() chains)
- Destructure props in function parameters
- Max function length: 50 lines
- No \`any\` types anywhere

# Styling
- Tailwind CSS utility classes only
- No inline styles
- Use cn() helper for conditional classes
- shadcn/ui components as building blocks

# Database
- Use Prisma ORM for all database operations
- No raw SQL queries
- Zod schemas for input validation
- Server Actions for data mutations

# Auth
- All server actions require auth checks
- Verify session server-side
- Return 401 for unauthenticated requests

# Payments
- NEVER log Stripe tokens or payment data
- Verify webhook signatures
- Use Stripe test keys in development
- Idempotency keys on payment operations

# Forbidden
- No \`eval()\` or \`Function()\`
- No unvalidated user input in queries
- No direct database queries from components
- No \`any\` types
- No console.log in production
- No hardcoded secrets
`,
    },
  },
  'react-dashboard': {
    name: 'React Admin Dashboard',
    description: 'Internal dashboard with charts, tables, and data visualization',
    files: {
      'AGENTS.md': `# React Dashboard — Agent Context

> Auto-generated template for dashboard projects

## Overview
An internal admin dashboard built with React 19, TypeScript, and Tailwind CSS.

## Tech Stack

| Layer | Technology |
|-------|-----------|
| Framework | React 19 + Vite |
| Language | TypeScript (strict) |
| Styling | Tailwind CSS |
| Charts | Recharts |
| Tables | TanStack Table |
| State | Zustand |
| Routing | React Router v7 |
| Testing | Vitest |

## Architecture

### State Management
- Zustand for global state
- React Query for server state
- Local state with useState/useReducer

### Data Flow
- API layer: centralized fetch with interceptors
- Error boundaries for graceful failures
- Loading states on all async operations
- Optimistic updates where appropriate

## Coding Standards

### TypeScript
- Strict mode — no \`any\` types
- All API responses typed with interfaces
- Use discriminated unions for state

### Components
- Compound component pattern for complex UIs
- Render props for customizable behavior
- Forward refs for wrapper components

### Styling
- Tailwind with custom design tokens
- Dark mode support via CSS variables
- Responsive breakpoints: sm/md/lg/xl

## Security

### Auth
- Token-based auth (JWT)
- Auto-refresh tokens
- Role-based menu items
- Session timeout after 30min inactivity

### Data
- Sanitize all user inputs
- Escape rendered HTML
- Rate limit API calls
- Audit log for sensitive actions

## Scripts

- \`npm run dev\` — Development
- \`npm run build\` — Production build
- \`npm run preview\` — Preview build
- \`npm run test\` — Unit tests
- \`npm run lint\` — ESLint check

---
*Generated by Vibe Coding — vibe sync --templates*
`,
      '.iderules': `# React Dashboard — IDE Rules

# Framework
- React 19 + Vite + TypeScript strict mode
- No class components — functional only
- Hooks for all state and side effects

# Code Style
- Named exports preferred
- async/await (no .then() chains)
- Destructure props in parameters
- Max 50 lines per function
- Custom hooks for reusable logic

# Styling
- Tailwind CSS utility classes
- CSS variables for theme (light/dark)
- No inline styles
- Responsive: mobile-first

# State
- Zustand for global
- React Query for server state
- useState for local UI state

# Forbidden
- No \`any\` types
- No prop drilling (>2 levels)
- No console.log in production
- No direct API calls from components (use hooks)
`,
    },
  },
  'api-service': {
    name: 'REST API Service',
    description: 'Node.js API with Fastify, Prisma, and OpenAPI docs',
    files: {
      'AGENTS.md': `# API Service — Agent Context

> Auto-generated template for API projects

## Overview
A Node.js REST API built with Fastify, Prisma ORM, and TypeScript.

## Tech Stack

| Layer | Technology |
|-------|-----------|
| Framework | Fastify |
| Language | TypeScript |
| Database | PostgreSQL + Prisma |
| Auth | JWT (jose library) |
| Validation | Zod |
| Docs | Scalar (OpenAPI) |
| Testing | Vitest |

## Architecture

### API Design
- RESTful resource-oriented URLs
- JSON request/response bodies
- Proper HTTP status codes
- Pagination: cursor-based for lists
- Filtering, sorting, search via query params

### Middleware Stack
1. Request logging (pino)
2. CORS
3. Rate limiting
4. Auth verification
5. Input validation (Zod)
6. Route handler
7. Error handler

## Coding Standards

### TypeScript
- Strict mode
- Shared types between API and consumers
- Zod schemas for runtime validation

### Error Handling
- Consistent error response format
- Operational vs programming errors
- Never leak stack traces in production
- Structured logging with correlation IDs

### Database
- Prisma migrations for schema changes
- Transactions for multi-step operations
- Connection pooling
- Query optimization with indexes

## Security

### Auth
- JWT access tokens (15min expiry)
- Refresh tokens (7 days, httpOnly cookie)
- Role-based access control
- Rate limiting per user and IP

### Validation
- Zod schemas for ALL inputs
- SQL injection prevention (Prisma)
- XSS prevention (output encoding)
- File upload validation (type, size, scan)

## Scripts

- \`npm run dev\` — Development with hot reload
- \`npm run build\` — Compile TypeScript
- \`npm run start\` — Production server
- \`npm run test\` — Unit tests
- \`npm run db:migrate\` — Run migrations
- \`npm run db:studio\` — Prisma Studio

---
*Generated by Vibe Coding — vibe sync --templates*
`,
      '.iderules': `# API Service — IDE Rules

# Framework
- Fastify + TypeScript strict mode
- Prisma ORM for database
- Zod for all input validation

# Code Style
- Named exports
- async/await (no .then())
- Destructure parameters
- Max 50 lines per function
- Error handling in every async function

# API Patterns
- Resource-based routes (/users, /orders)
- Proper HTTP methods (GET, POST, PATCH, DELETE)
- Consistent response format
- Pagination on list endpoints

# Database
- Prisma for ALL queries
- No raw SQL
- Transactions for related writes
- Migration for schema changes

# Security
- Validate ALL inputs with Zod
- Auth middleware on protected routes
- No secrets in code
- Rate limiting on all endpoints

# Forbidden
- No \`any\` types
- No raw SQL
- No console.log (use pino logger)
- No unhandled promise rejections
`,
    },
  },
};

export const PROMPTS_LIBRARY: Record<string, PromptItem[]> = {
  'component-patterns': [
    {
      name: 'Compound Component',
      description: 'Create a reusable compound component pattern',
      prompt: 'Create a compound component called [ComponentName] that follows this pattern:\n\n1. A parent component that manages shared state via React Context\n2. Sub-components that access the shared state\n3. Usage should look like:\n   <[ComponentName]>\n     <[ComponentName].Header>...</[ComponentName].Header>\n     <[ComponentName].Body>...</[ComponentName].Body>\n   </[ComponentName]>\n\nInclude:\n- TypeScript types for all props\n- Context provider with error boundary\n- Custom hook for consuming the context\n- Example usage in a Storybook story',
    },
    {
      name: 'Data Table',
      description: 'Sortable, filterable data table with pagination',
      prompt: 'Create a DataTable component with:\n\n1. Column definitions with type-safe config\n2. Sorting (click column headers)\n3. Filtering (per-column search)\n4. Pagination (page size selector)\n5. Row selection (checkboxes)\n6. Empty state\n7. Loading skeleton\n\nUse:\n- TanStack Table (react-table) as the foundation\n- Tailwind CSS for styling\n- shadcn/ui components where appropriate\n- TypeScript generics for row data type\n\nInclude a demo with 100+ rows of mock data.',
    },
  ],
  'auth-patterns': [
    {
      name: 'OAuth + Credentials Auth',
      description: 'Full auth system with NextAuth.js',
      prompt: 'Implement a complete authentication system with:\n\n1. OAuth providers (Google, GitHub)\n2. Credentials provider (email/password)\n3. JWT session strategy with refresh tokens\n4. Middleware for route protection\n5. Role-based access control (user/admin)\n6. Sign in / Sign up pages\n7. Password reset flow\n8. Session expiration handling\n\nTech: Next.js 14 App Router, NextAuth.js v5, Prisma, TypeScript\n\nInclude:\n- Prisma schema for User and Account models\n- Auth configuration with all providers\n- Middleware for protected routes\n- Server-side session helpers\n- Client-side auth hook\n- Complete sign-in page with OAuth buttons',
    },
    {
      name: 'API Authentication',
      description: 'JWT-based auth for API routes',
      prompt: 'Implement JWT authentication for a REST API:\n\n1. Token generation on login\n2. Token verification middleware\n3. Refresh token rotation\n4. Token blacklist on logout\n5. Rate limiting on auth endpoints\n6. CORS configuration\n\nTech: Fastify, jose (JWT), Prisma, bcrypt\n\nInclude:\n- Login/Register route handlers\n- Auth middleware (Fastify plugin)\n- Token utilities (sign, verify, refresh)\n- Integration tests for all auth flows',
    },
  ],
  'database-patterns': [
    {
      name: 'CRUD with Prisma',
      description: 'Complete CRUD operations with Prisma ORM',
      prompt: 'Implement CRUD operations for a [Resource] entity using Prisma:\n\n1. Create (with validation)\n2. Read (single + list with pagination)\n3. Update (partial updates)\n4. Delete (soft delete with deletedAt)\n5. Search (full-text)\n6. Filtering and sorting\n\nInclude:\n- Prisma schema definition\n- Zod schemas for input validation\n- Server Actions or Route Handlers\n- Error handling with specific error types\n- Database transactions where needed\n- Unit tests with mocked Prisma client',
    },
  ],
  'testing-patterns': [
    {
      name: 'Component Testing',
      description: 'Testing React components with Vitest',
      prompt: 'Write comprehensive tests for a [ComponentName] component:\n\n1. Rendering test (default props)\n2. User interaction tests (click, type, submit)\n3. Edge cases (empty data, loading, error states)\n4. Accessibility tests (keyboard navigation, ARIA)\n5. Snapshot test for UI regression\n\nTech: Vitest, React Testing Library, user-event, jsdom\n\nInclude:\n- Test setup and utilities\n- Mock data factories\n- MSW setup for API mocking\n- Coverage configuration\n- CI-ready test script',
    },
  ],
};

export function getTemplateIds(): string[] {
  return Object.keys(TEMPLATES);
}

export function getTemplate(id: string): Template | undefined {
  return TEMPLATES[id];
}

export function listTemplates(): { id: string; name: string; description: string }[] {
  return Object.entries(TEMPLATES).map(([id, t]) => ({ id, name: t.name, description: t.description }));
}

export function getPromptCategoryIds(): string[] {
  return Object.keys(PROMPTS_LIBRARY);
}

export function listPromptCategories(): { id: string; label: string; count: number }[] {
  return Object.entries(PROMPTS_LIBRARY).map(([id, prompts]) => ({
    id,
    label: id.replace(/-/g, ' ').replace(/\b\w/g, (l) => l.toUpperCase()),
    count: prompts.length,
  }));
}

export function getPromptsByCategory(categoryId: string): PromptItem[] {
  return PROMPTS_LIBRARY[categoryId] || [];
}

export function getPrompt(categoryId: string, promptIndex: number): PromptItem | undefined {
  return PROMPTS_LIBRARY[categoryId]?.[promptIndex];
}

export function defaultPromptFileName(promptName: string): string {
  return `${promptName.toLowerCase().replace(/\s+/g, '-')}-prompt.md`;
}

export function formatPromptFileContent(item: PromptItem): string {
  return `# ${item.name}\n\n> ${item.description}\n\n## Prompt\n\n${item.prompt}\n\n---\n*From Vibe Coding Prompt Library — vibe sync --prompts*\n`;
}

