import type { DetectedStack } from '../utils/detect.js';

export function generateAgentsMd(projectName: string, stack: DetectedStack): string {
  return `# ${projectName} — Agent Context

> Auto-generated by Vibe Coding CLI
> Last updated: ${new Date().toISOString().split('T')[0]}

## Overview
A ${stack.framework} project using ${stack.language}.

## Tech Stack

| Layer | Technology |
|-------|-----------|
| Framework | ${stack.framework} |
| Language | ${stack.language} |
| Package Manager | ${stack.packageManager} |
${stack.hasDatabase ? '| Database | Yes (detected)' : ''}
${stack.hasAuth ? '| Auth | Yes (detected)' : ''}
${stack.hasTests ? '| Testing | Yes (detected)' : ''}

## Coding Standards

### ${stack.language === 'typescript' ? 'TypeScript' : 'JavaScript'}
${stack.language === 'typescript' ? '- Strict mode enabled\n- All functions must have typed parameters and return types' : '- Use modern ES2022+ features\n- Consistent code style'}

### General
- Use named exports preferred over default exports
- async/await (no .then() chains)
- Max function length: 50 lines

### Security
- Input validation on ALL user inputs
- No hardcoded secrets or API keys
- No console.log in production code

## Git Workflow

| Branch | Purpose |
|--------|---------|
| \`main\` | Production — no direct commits |
| \`develop\` | Integration branch |
| \`feature/*\` | New features |

### Commits
Format: \`type(scope): description\`
Types: feat, fix, docs, test, refactor, security, deps

## Deployment Checklist

- [ ] All tests pass
- [ ] TypeScript compiles without errors
- [ ] No console.log statements in production code
- [ ] Environment variables configured
`;
}

export function generateCursorRules(stack: DetectedStack): string {
  return `# Global Rules — Project

# Framework
- This is a ${stack.framework} project using ${stack.language}
${stack.language === 'typescript' ? '- Strict mode — no \`any\` types' : ''}

# Code Style
- Named exports preferred
- async/await (no .then())
- Max function length: 50 lines

# Security
- Input validation on ALL inputs
- No hardcoded secrets
- No console.log in production

# Forbidden
- No eval() or Function()
- No inline styles (use CSS/Tailwind)
`;
}
