/**
 * Managed-block markers for `--merge` mode.
 *
 * The generated part of AGENTS.md is wrapped in HTML-comment markers so user
 * content outside the markers is preserved on subsequent runs. The begin
 * marker may carry an informational suffix on the same comment line, e.g.:
 * <!-- vibe:begin — auto-generated by @vibecoding/cli; edit outside these markers -->
 */
export const MARKER_BEGIN = '<!-- vibe:begin -->';
export const MARKER_END = '<!-- vibe:end -->';

const BEGIN_PREFIX = '<!-- vibe:begin';
const END_PREFIX = '<!-- vibe:end';
const BEGIN_NOTE = 'auto-generated by @vibecoding/cli; edit outside these markers';

/** Wraps generated content in managed markers. */
export function wrapInMarkers(content: string): string {
  return `${BEGIN_PREFIX} — ${BEGIN_NOTE} -->\n${content.trimEnd()}\n${MARKER_END}\n`;
}

/**
 * Merges freshly generated content into an existing AGENTS.md.
 *
 * - If `existing` already contains both markers, only the block between them
 *   (inclusive) is replaced — everything outside the markers is preserved.
 * - If there are no markers, the generated block is appended at the end,
 *   separated from the existing content by a horizontal rule.
 */
export function mergeIntoExisting(existing: string, generated: string): string {
  const wrapped = wrapInMarkers(generated);
  if (existing.trim() === '') return wrapped;

  const lines = existing.split('\n');
  const beginLine = lines.findIndex((line) => line.includes(BEGIN_PREFIX));
  let endLine = -1;
  if (beginLine !== -1) {
    for (let i = beginLine + 1; i < lines.length; i++) {
      if (lines[i].includes(END_PREFIX)) {
        endLine = i;
        break;
      }
    }
  }

  if (beginLine !== -1 && endLine !== -1) {
    return [
      ...lines.slice(0, beginLine),
      ...wrapped.trimEnd().split('\n'),
      ...lines.slice(endLine + 1),
    ].join('\n');
  }

  return existing.trimEnd() + '\n\n---\n\n' + wrapped;
}
